import { c as create_ssr_component, a as setContext, b as add_attribute, v as validate_component } from "../../chunks/ssr.js";
const logo = "/_app/immutable/assets/Logo_Linner_Seidemann_Bildmarke_2023_white.af1ea60d.png";
const Header_svelte_svelte_type_style_lang = "";
const css$1 = {
  code: 'nav.svelte-10becwx.svelte-10becwx.svelte-10becwx{padding:0.8rem 2rem;background-color:#00336A}@media(max-width: 672px){nav.svelte-10becwx.svelte-10becwx.svelte-10becwx{padding:0.8rem 1rem}}nav.svelte-10becwx .nav_lg.svelte-10becwx.svelte-10becwx{display:flex;flex-direction:row;justify-content:end}@media(max-width: 672px){nav.svelte-10becwx .nav_lg.svelte-10becwx.svelte-10becwx{display:none}}nav.svelte-10becwx .nav_lg ul.svelte-10becwx.svelte-10becwx{display:flex;flex-direction:row;justify-content:flex-end;margin-top:0;margin-bottom:0.5rem}nav.svelte-10becwx .nav_lg ul li.svelte-10becwx.svelte-10becwx{list-style:none;padding:0 1rem;font-family:"Libre Baskerville", serif;font-size:1.2rem;margin-top:0.5rem}nav.svelte-10becwx .nav_lg ul li.svelte-10becwx+li.svelte-10becwx{border-left:1px solid #FFF}nav.svelte-10becwx .nav_lg ul li a.svelte-10becwx.svelte-10becwx{text-decoration:none}nav.svelte-10becwx .nav_mobile.svelte-10becwx.svelte-10becwx{display:none}@media(max-width: 672px){nav.svelte-10becwx .nav_mobile.svelte-10becwx.svelte-10becwx{display:inline-block;cursor:pointer;width:100%}nav.svelte-10becwx .nav_mobile img.svelte-10becwx.svelte-10becwx{float:left}nav.svelte-10becwx .nav_mobile .toggler.svelte-10becwx.svelte-10becwx{float:right;background-color:#00336A;border:none}nav.svelte-10becwx .nav_mobile .toggler .bar1.svelte-10becwx.svelte-10becwx,nav.svelte-10becwx .nav_mobile .toggler .bar2.svelte-10becwx.svelte-10becwx,nav.svelte-10becwx .nav_mobile .toggler .bar3.svelte-10becwx.svelte-10becwx{width:35px;height:5px;background-color:#FFF;margin:6px 0;transition:0.4s}nav.svelte-10becwx .nav_mobile ul.svelte-10becwx.svelte-10becwx{padding-left:0;text-align:center;margin-top:50px}nav.svelte-10becwx .nav_mobile ul li.svelte-10becwx.svelte-10becwx{list-style:none;font-family:"Libre Baskerville", serif}nav.svelte-10becwx .nav_mobile ul li.svelte-10becwx+li.svelte-10becwx{border-top:1px solid #FFF;padding-top:1rem}nav.svelte-10becwx .nav_mobile ul li a.svelte-10becwx.svelte-10becwx{color:#FFF;text-decoration:none}}',
  map: null
};
const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let isOpen = false;
  setContext("mobileMenu", { isOpen });
  $$result.css.add(css$1);
  return `<header><nav class="svelte-10becwx"><div class="nav_lg svelte-10becwx" data-svelte-h="svelte-1v872b4"><ul class="svelte-10becwx"><li class="svelte-10becwx"><a class="nav-link svelte-10becwx" href="/">Home</a></li> <li class="svelte-10becwx"><a class="nav-link svelte-10becwx" href="/services">Services</a></li> <li class="svelte-10becwx"><a class="nav-link svelte-10becwx" href="/kooperationen">Kooperationen</a></li> <li class="svelte-10becwx"><a class="nav-link svelte-10becwx" href="/kontakt">Kontakt</a></li></ul></div> <div class="nav_mobile svelte-10becwx"><a href="/" class="svelte-10becwx" data-svelte-h="svelte-1f95fc0"><img${add_attribute("src", logo, 0)} alt="Linner Seidemann Wirtschaftsprüfung Logo" width="45" class="svelte-10becwx"></a> <button class="toggler svelte-10becwx" data-svelte-h="svelte-v838h0"><div class="bar1 svelte-10becwx"></div> <div class="bar2 svelte-10becwx"></div> <div class="bar3 svelte-10becwx"></div></button> ${``}</div></nav> </header>`;
});
const global = "";
const _layout_svelte_svelte_type_style_lang = "";
const css = {
  code: ".app.svelte-34bbk8.svelte-34bbk8{display:flex;flex-direction:column;min-height:100vh}main.svelte-34bbk8.svelte-34bbk8{flex:1;display:flex;flex-direction:column;width:100%;margin:0 auto;box-sizing:border-box}footer.svelte-34bbk8.svelte-34bbk8{display:flex;flex-direction:column;justify-content:center;align-items:center;padding:0.8rem;background-color:#00336A;color:#FFF}footer.svelte-34bbk8 p.svelte-34bbk8{margin:0}footer.svelte-34bbk8 p span.svelte-34bbk8{margin:0.8rem}footer.svelte-34bbk8 a.svelte-34bbk8{text-decoration:none}@media(max-width: 672px){footer.svelte-34bbk8 .footer_lg.svelte-34bbk8{display:none}}@media(min-width: 673px){footer.svelte-34bbk8 .footer_mobile.svelte-34bbk8{display:none}}@media(max-width: 672px){footer.svelte-34bbk8 .footer_mobile.svelte-34bbk8{display:flex;flex-direction:column}footer.svelte-34bbk8 .footer_mobile p.svelte-34bbk8{text-align:center}footer.svelte-34bbk8 .footer_mobile ul.svelte-34bbk8{padding-left:0;display:flex;flex-direction:column;text-align:center;margin-top:0.5rem}footer.svelte-34bbk8 .footer_mobile ul li.svelte-34bbk8{border-top:1px solid #FFF;list-style:none;padding-top:1rem}}",
  map: null
};
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<div class="app svelte-34bbk8">${validate_component(Header, "Header").$$render($$result, {}, {}, {})} <main class="svelte-34bbk8">${slots.default ? slots.default({}) : ``}</main> <footer class="svelte-34bbk8" data-svelte-h="svelte-sx8w4v"><div class="footer_lg svelte-34bbk8"><p class="svelte-34bbk8">© 2023 Linner | Seidemann PartG mbB Wirtschaftsprüfungsgesellschaft <span class="svelte-34bbk8">•</span> <a href="/impressum" class="svelte-34bbk8">Impressum</a> <span class="svelte-34bbk8">•</span> <a href="/datenschutz" class="svelte-34bbk8">Datenschutz</a> <span class="svelte-34bbk8">•</span> <a href="/bildrechte" class="svelte-34bbk8">Bildrechte</a></p></div> <div class="footer_mobile svelte-34bbk8"><p class="svelte-34bbk8">© 2023 Linner | Seidemann PartG mbB Wirtschaftsprüfungsgesellschaft</p> <ul class="svelte-34bbk8"><li class="svelte-34bbk8"><a href="/impressum" class="svelte-34bbk8">Impressum</a></li> <li class="svelte-34bbk8"><a href="/datenschutz" class="svelte-34bbk8">Datenschutz</a></li> <li class="svelte-34bbk8"><a href="/bildrechte" class="svelte-34bbk8">Bildrechte</a></li></ul></div></footer> </div>`;
});
export {
  Layout as default
};
