import { c as create_ssr_component, b as add_attribute, v as validate_component } from "../../chunks/ssr.js";
const logo = "/_app/immutable/assets/Logo_Linner_Seidemann_Bildmarke_2023_white.af1ea60d.png";
const Header_svelte_svelte_type_style_lang = "";
const css$1 = {
  code: 'nav.svelte-6q6n2n.svelte-6q6n2n.svelte-6q6n2n{padding:0.8rem 2rem;background-color:#00336A}@media(max-width: 672px){nav.svelte-6q6n2n.svelte-6q6n2n.svelte-6q6n2n{padding:0.8rem 1rem}}nav.svelte-6q6n2n .nav_lg.svelte-6q6n2n.svelte-6q6n2n{display:flex;flex-direction:row;justify-content:end}@media(max-width: 672px){nav.svelte-6q6n2n .nav_lg.svelte-6q6n2n.svelte-6q6n2n{display:none}}nav.svelte-6q6n2n .nav_lg ul.svelte-6q6n2n.svelte-6q6n2n{display:flex;flex-direction:row;justify-content:flex-end;margin-top:0;margin-bottom:0.5rem}nav.svelte-6q6n2n .nav_lg ul li.svelte-6q6n2n.svelte-6q6n2n{list-style:none;padding:0 1rem;font-family:"Libre Baskerville", serif;font-size:1.2rem;margin-top:0.5rem}nav.svelte-6q6n2n .nav_lg ul li.svelte-6q6n2n+li.svelte-6q6n2n{border-left:1px solid #FFF}nav.svelte-6q6n2n .nav_lg ul li a.svelte-6q6n2n.svelte-6q6n2n{text-decoration:none}nav.svelte-6q6n2n .nav_mobile.svelte-6q6n2n.svelte-6q6n2n{display:none}@media(max-width: 672px){nav.svelte-6q6n2n .nav_mobile.svelte-6q6n2n.svelte-6q6n2n{display:inline-block;cursor:pointer;width:100%}nav.svelte-6q6n2n .nav_mobile img.svelte-6q6n2n.svelte-6q6n2n{float:left}nav.svelte-6q6n2n .nav_mobile .toggler.svelte-6q6n2n.svelte-6q6n2n{float:right;background-color:#00336A;border:none}nav.svelte-6q6n2n .nav_mobile .toggler .bar1.svelte-6q6n2n.svelte-6q6n2n,nav.svelte-6q6n2n .nav_mobile .toggler .bar2.svelte-6q6n2n.svelte-6q6n2n,nav.svelte-6q6n2n .nav_mobile .toggler .bar3.svelte-6q6n2n.svelte-6q6n2n{width:35px;height:5px;background-color:#FFF;margin:6px 0;transition:0.4s}nav.svelte-6q6n2n .nav_mobile ul.svelte-6q6n2n.svelte-6q6n2n{padding-left:0;text-align:center;margin-top:50px}nav.svelte-6q6n2n .nav_mobile ul li.svelte-6q6n2n.svelte-6q6n2n{list-style:none;font-family:"Libre Baskerville", serif}nav.svelte-6q6n2n .nav_mobile ul li.svelte-6q6n2n+li.svelte-6q6n2n{border-top:1px solid #FFF;padding-top:1rem}nav.svelte-6q6n2n .nav_mobile ul li a.svelte-6q6n2n.svelte-6q6n2n{color:#FFF}}',
  map: null
};
const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$1);
  return `<header><nav class="svelte-6q6n2n"><div class="nav_lg svelte-6q6n2n" data-svelte-h="svelte-1v872b4"><ul class="svelte-6q6n2n"><li class="svelte-6q6n2n"><a class="nav-link svelte-6q6n2n" href="/">Home</a></li> <li class="svelte-6q6n2n"><a class="nav-link svelte-6q6n2n" href="/services">Services</a></li> <li class="svelte-6q6n2n"><a class="nav-link svelte-6q6n2n" href="/kooperationen">Kooperationen</a></li> <li class="svelte-6q6n2n"><a class="nav-link svelte-6q6n2n" href="/kontakt">Kontakt</a></li></ul></div> <div class="nav_mobile svelte-6q6n2n"><a href="/" class="svelte-6q6n2n" data-svelte-h="svelte-1f95fc0"><img${add_attribute("src", logo, 0)} alt="Linner Seidemann Wirtschaftsprüfung Logo" width="45" class="svelte-6q6n2n"></a> <button class="toggler svelte-6q6n2n" data-svelte-h="svelte-10oavbu"><div class="bar1 svelte-6q6n2n"></div> <div class="bar2 svelte-6q6n2n"></div> <div class="bar3 svelte-6q6n2n"></div></button> ${``}</div></nav> </header>`;
});
const global = "";
const _layout_svelte_svelte_type_style_lang = "";
const css = {
  code: ".app.svelte-1n7hb6p.svelte-1n7hb6p{display:flex;flex-direction:column;min-height:100vh}main.svelte-1n7hb6p.svelte-1n7hb6p{flex:1;display:flex;flex-direction:column;width:100%;margin:0 auto;box-sizing:border-box}footer.svelte-1n7hb6p.svelte-1n7hb6p{display:flex;flex-direction:column;justify-content:center;align-items:center;padding:0.8rem;background-color:#00336A;color:#FFF}footer.svelte-1n7hb6p p.svelte-1n7hb6p{margin:0}footer.svelte-1n7hb6p p span.svelte-1n7hb6p{margin:0.8rem}@media(max-width: 672px){footer.svelte-1n7hb6p .footer_lg.svelte-1n7hb6p{display:none}}@media(min-width: 673px){footer.svelte-1n7hb6p .footer_mobile.svelte-1n7hb6p{display:none}}@media(max-width: 672px){footer.svelte-1n7hb6p .footer_mobile.svelte-1n7hb6p{display:flex;flex-direction:column}footer.svelte-1n7hb6p .footer_mobile p.svelte-1n7hb6p{text-align:center}footer.svelte-1n7hb6p .footer_mobile ul.svelte-1n7hb6p{padding-left:0;display:flex;flex-direction:column;text-align:center;margin-top:0.5rem}footer.svelte-1n7hb6p .footer_mobile ul li.svelte-1n7hb6p{border-top:1px solid #FFF;list-style:none;padding-top:1rem}}",
  map: null
};
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<div class="app svelte-1n7hb6p">${validate_component(Header, "Header").$$render($$result, {}, {}, {})} <main class="svelte-1n7hb6p">${slots.default ? slots.default({}) : ``}</main> <footer class="svelte-1n7hb6p" data-svelte-h="svelte-sx8w4v"><div class="footer_lg svelte-1n7hb6p"><p class="svelte-1n7hb6p">© 2023 Linner | Seidemann PartG mbB Wirtschaftsprüfungsgesellschaft <span class="svelte-1n7hb6p">•</span> <a href="/impressum">Impressum</a> <span class="svelte-1n7hb6p">•</span> <a href="/datenschutz">Datenschutz</a> <span class="svelte-1n7hb6p">•</span> <a href="/bildrechte">Bildrechte</a></p></div> <div class="footer_mobile svelte-1n7hb6p"><p class="svelte-1n7hb6p">© 2023 Linner | Seidemann PartG mbB Wirtschaftsprüfungsgesellschaft</p> <ul class="svelte-1n7hb6p"><li class="svelte-1n7hb6p"><a href="/impressum">Impressum</a></li> <li class="svelte-1n7hb6p"><a href="/datenschutz">Datenschutz</a></li> <li class="svelte-1n7hb6p"><a href="/bildrechte">Bildrechte</a></li></ul></div></footer> </div>`;
});
export {
  Layout as default
};
