import { c as create_ssr_component, e as escape, b as add_attribute, v as validate_component } from "../../chunks/ssr.js";
import { B as Background } from "../../chunks/Background.js";
const LinnerSeidemannLogoBig = "/_app/immutable/assets/Logo_Linner_Seidemann_2023_white.6d9ba326.png";
const intro_vid = "/_app/immutable/assets/intro-video.60a92b17.mp4";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: ".video_wrapper.svelte-apphd4.svelte-apphd4{position:relative;overflow:hidden;text-align:center;display:flex;align-items:center;justify-content:center;height:50vh}.video_wrapper.svelte-apphd4 video.svelte-apphd4{object-fit:cover;position:absolute;top:0;left:0;height:100%;width:100%}.video_wrapper.svelte-apphd4 h1.svelte-apphd4{position:relative;color:#FFF;text-shadow:1px 1px 2px #00336A}img.svelte-apphd4.svelte-apphd4{width:60%;margin:0 auto}.content.svelte-apphd4.svelte-apphd4{width:80%;margin:0 auto;padding:2rem 0}.content.svelte-apphd4 .content_split.svelte-apphd4{display:flex;flex-direction:row}.content.svelte-apphd4 .content_split p.svelte-apphd4{width:50%;padding:0 2rem}.content.svelte-apphd4 hr.svelte-apphd4{margin:3rem 2rem}.cookies.svelte-apphd4.svelte-apphd4{position:sticky;bottom:0;background:#152b43;text-align:center;padding:1.5rem;padding-top:0;color:#FFF;border-top:1px solid #FFF;border-bottom:1px solid #FFF}.accepted.svelte-apphd4.svelte-apphd4{display:none}@media(max-width: 1055px){img.svelte-apphd4.svelte-apphd4{width:80%}.content.svelte-apphd4 .content_split.svelte-apphd4{flex-direction:column}.content.svelte-apphd4 .content_split p.svelte-apphd4{width:100%;margin:1.5rem 0}.content.svelte-apphd4 hr.svelte-apphd4{display:none}}@media(max-width: 672px){img.svelte-apphd4.svelte-apphd4{width:100%}.content.svelte-apphd4.svelte-apphd4{width:100%}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-j3kba1_START -->${$$result.title = `<title>Linner Seidemann Wirtschaftsprüfung</title>`, ""}<meta name="description" content="Linner Seidemann Wirtschaftsprüfung"><!-- HEAD_svelte-j3kba1_END -->`, ""} <div class="video_wrapper svelte-apphd4" data-svelte-h="svelte-c0xyjs"><video id="background-video" autoplay loop muted poster="${escape(LinnerSeidemannLogoBig, true) + "}"}" class="svelte-apphd4"><source${add_attribute("src", intro_vid, 0)} type="video/mp4"></video> <h1 class="svelte-apphd4">Linner | Seidemann<br>Wirtschafts­prüfung</h1></div> <img${add_attribute("src", LinnerSeidemannLogoBig, 0)} alt="Linner Seidemann Wirtschaftsprüfung Logo" class="svelte-apphd4"> ${validate_component(Background, "Background").$$render($$result, {}, {}, {
    section_content: () => {
      return `<div slot="section_content" class="content svelte-apphd4" data-svelte-h="svelte-5q9kta"><div class="content_split svelte-apphd4"><p class="svelte-apphd4">Unsere Kanzlei zeichnet sich durch eine dynamische Struktur aus. Mit fundiertem Fachwissen und Leidenschaft für die Prüfung und Bewertung von Unternehmen in verschiedenen Wirtschaftszweigen sind wir Ihr verlässlicher Ansprechpartner.</p> <p class="svelte-apphd4">Unsere langjährige Erfahrung, fundierten Fachkenntnisse und spezialisierten Branchenkenntnisse in den Bereichen Kredit-, Finanzdienstleistungs- und Wertpapierinstituten sowie Leasinggesellschaften qualifizieren uns als Ihren professionellen Partner auf höchstem Niveau.</p></div> <hr class="svelte-apphd4"> <div class="content_split svelte-apphd4"><p class="svelte-apphd4">Wir verstehen die spezifischen Anforderungen und regulatorischen Herausforderungen, denen unsere Mandanten gegenüberstehen, und bieten maßgeschneiderte Lösungen, die ihnen helfen, ihre Ziele zu erreichen.</p> <p class="svelte-apphd4">Unser Engagement für Exzellenz spiegelt sich in der Qualität unserer Arbeit wider. Wir sind stolz darauf, unseren Mandanten durch fundierte Analysen, klare Kommunikation und effiziente Prozesse zu unterstützen.</p></div></div>`;
    }
  })} <div class="${["cookies svelte-apphd4", ""].join(" ").trim()}"><p data-svelte-h="svelte-1b8e5ax">Mit der Verwendung unserer Webseite erklären Sie sich mit den Datenschutzbedingungen einverstanden. <a href="/datenschutz">Mehr erfahren</a></p> <button id="toggle" data-svelte-h="svelte-a2uhu0">Einverstanden</button> </div>`;
});
export {
  Page as default
};
