import { c as create_ssr_component } from "../../../chunks/ssr.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: '.intro.svelte-yfiyhe.svelte-yfiyhe{background-image:url("$lib/images/computer-820281_1920.jpg");background-repeat:no-repeat;background-size:cover;height:30vh;display:flex;align-items:center;justify-content:center}.service_wrap.svelte-yfiyhe.svelte-yfiyhe{width:80%;margin-left:auto;margin-right:auto;margin-top:2rem;background-color:#00558e;padding:2rem;display:flex;flex-direction:row}.service_wrap.svelte-yfiyhe .service_headline.svelte-yfiyhe{justify-content:center;flex-grow:1}.service_wrap.svelte-yfiyhe .service_content.svelte-yfiyhe{flex-grow:8}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-13flzj7_START -->${$$result.title = `<title>Services</title>`, ""}<meta name="description" content="Services"><!-- HEAD_svelte-13flzj7_END -->`, ""} <div class="intro svelte-yfiyhe" data-svelte-h="svelte-ckwyyf"><h1>Services</h1></div> <div class="service_wrap svelte-yfiyhe" data-svelte-h="svelte-yyfifd"><div class="service_headline svelte-yfiyhe"> <h2>AUDIT – FINANCIAL SERVICES</h2></div> <ul class="service_content svelte-yfiyhe"><li>Jahres- und Konzernabschlussprüfung von
			<ul><li>Wertpapierinstituten</li> <li>Finanzdienstleistungsinstituten</li> <li>Kreditinstituten</li> <li>Kapitalverwaltungsgesellschaften</li> <li>Leasinggesellschaften</li></ul></li> <li>WpHG-Prüfung
			<ul><li>Prüfung nach § 89 Abs. 1 Satz 1 WpHG</li></ul></li> <li>Prüferische Durchsicht von Abschlüssen</li></ul></div> <div class="service_wrap svelte-yfiyhe" data-svelte-h="svelte-19r3tza"><div class="service_headline svelte-yfiyhe"> <h2>AUDIT – CORPORATE CLIENTS</h2></div> <ul class="service_content svelte-yfiyhe"><li>Jahres- und Konzernabschlussprüfung nach deutschen, handelsrechtlichen Vorschriften (HGB)</li> <li>Jahres- und Konzernabschlussprüfung nach internationalen Vorschriften (IFRS)</li> <li>Prüferische Durchsicht von Abschlüssen</li> <li>Sonderprüfungen (u.a. MaBV, FinVermV, Sonderprüfungen nach dem AktG, GmbHG, UmwG)</li></ul></div> <div class="service_wrap svelte-yfiyhe" data-svelte-h="svelte-1g8w17t"><div class="service_headline svelte-yfiyhe"> <h2>VALUATION &amp; TRANSACTION SERVICES</h2></div> <ul class="service_content svelte-yfiyhe"><li>Unternehmensbewertung nach IDW S 1</li> <li>Bewertung von kleinen und mittleren Unternehmen</li> <li>Bewertung von einzelnen Vermögenswerten</li> <li>Indikative Wertermittlungen</li> <li>Financial Due Diligence</li> <li>Ankaufsbewertung gemäß KAGB</li></ul></div> <div class="service_wrap svelte-yfiyhe" data-svelte-h="svelte-kunbw"><div class="service_headline svelte-yfiyhe"> <h2>INSOURCING &amp; OUTSOURCING</h2></div> <ul class="service_content svelte-yfiyhe"><li>Innenrevision</li> <li>Funktion des Geldwäsche-Beauftragten</li> <li>Funktion des Compliance-Beauftragten</li> <li>Umsetzung neuer Regularien im Banken- und Finanzdienstleistungsbereich</li> <li>Risikomanagementfunktion</li></ul> </div>`;
});
export {
  Page as default
};
